# Generated by Django 3.0 on 2019-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feel_on_compltng_projct', models.TextField()),
                ('projct_on_hold', models.TextField()),
                ('finished_wrk', models.TextField()),
                ('projct_name', models.CharField(max_length=150)),
                ('why_to_finish_projct', models.TextField()),
                ('my_dream_day', models.TextField()),
                ('when_will_finish_projct', models.DateTimeField()),
                ('tools_and_tech', models.TextField()),
                ('stay_focusd', models.TextField()),
            ],
        ),
    ]
