# Generated by Django 3.0 on 2020-01-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionset',
            old_name='feel_on_compltng_projct',
            new_name='feel_on_completing_project',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='finished_wrk',
            new_name='finished_project',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='projct_on_hold',
            new_name='how_to_stay_focused',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='projct_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='stay_focusd',
            new_name='projects_on_hold',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='when_will_finish_projct',
            new_name='when_will_finish_project',
        ),
        migrations.RenameField(
            model_name='questionset',
            old_name='why_to_finish_projct',
            new_name='why_to_finish_project',
        ),
    ]
